In [1]:
import numpy as np

We are goin to study about the different functions of the numpy.

In [2]:
#here it will return True when i==j and will create 3x3 matrix

np.fromfunction(lambda i , j : i == j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [3]:
#Now performing the multiplication operation of matrix using from funciton

np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [4]:
#using iter function 

iterable = (i**2 for i in range (5))

In [5]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [6]:
#It will seperate  string from the- Sep = " 'given value'"
np.fromstring('1122@456', sep = '@')

array([1122.,  456.])

In [7]:
np.fromstring('4,5,6,7,8', sep = ',')

array([4., 5., 6., 7., 8.])

Numpy data Type : 

In [8]:
l = [1,2,3,4]

In [9]:
ar = np.array(l)

In [10]:
ar

array([1, 2, 3, 4])

ndim : to find the dimension of the array

In [11]:

ar.ndim

1

In [12]:
#Creating a 2d array

ar2 = np.array([[2,3,4] , [3,4,5]])

In [13]:
ar2.ndim #We can see this is 2 dimensional array

2

In [14]:
#To check the size or number of the element in the array 

ar.size

4

In [15]:
ar2.size

6

In [16]:
#To check the size of the array
ar.shape

(4,)

In [17]:

ar2.shape #Here output 2 denotes the row and 3 denotes the column

(2, 3)

In [18]:
ar2.dtype

dtype('int64')

In [19]:
ar22 =  np.array([[1,4,2.5,44], (2,12,34,67)])

In [20]:
ar22

array([[ 1. ,  4. ,  2.5, 44. ],
       [ 2. , 12. , 34. , 67. ]])

In [21]:
ar22.dtype 

#Float number will make space for all the in values and alll will be turn into the float

dtype('float64')

Range function and arrange function :

Arange function : Its same like range function but it also take decimanl values and can also jump in decimal values which is not possible using range function 

In [22]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [23]:
ag = np.arange(2.4, 5.8, .2)

In [24]:
ag

array([2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8,
       5. , 5.2, 5.4, 5.6])

In [25]:
list(ag) #Converting it into list 

[2.4,
 2.6,
 2.8000000000000003,
 3.0000000000000004,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.8000000000000025,
 5.000000000000002,
 5.200000000000003,
 5.400000000000002,
 5.600000000000003]

In [26]:
#using linspace function 

np.linspace(1,5,10)
#it wil divide 1 to 5 into 10 equal part and then return all the values

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [27]:
np.linspace(0,100,4)

array([  0.        ,  33.33333333,  66.66666667, 100.        ])

In [28]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
np.zeros((3,4)) #Will make 3*4 matrix of 0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
ar3 = np.zeros((3,4,2)) #3 matrix of 4,2

In [31]:
ar3



array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [32]:
#np.ones() function return 1 instead of 0,reamin same like zeros functiuon 

np.ones(4)

array([1., 1., 1., 1.])

In [33]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
op = np.ones((3,4,4))

In [37]:
op +2  #will ad 2 in every values

#Can also add the decimanl numbers

array([[[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]],

       [[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]],

       [[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]])

In [38]:

op

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [39]:
#np.empty matrix is used to create an empty matrix

np.empty((3,3,5))

array([[[ 4.65400214e-310,  0.00000000e+000,  6.90486178e-310,
          7.45584579e+184,  6.90486178e-310],
        [ 6.90486178e-310,  3.89986767e+004,  6.90486178e-310,
          6.90486192e-310,  7.46440351e-200],
        [ 6.90486178e-310,  6.90486189e-310,  2.65101876e+089,
          6.90486178e-310,  6.90486178e-310]],

       [[ 1.66609087e-158,  6.90486191e-310,  6.90486194e-310,
         -7.77929461e+137,  6.90486178e-310],
        [ 4.65341413e-310,  5.61217478e+274,  6.90486360e-310,
          6.90486178e-310, -1.51089875e+306],
        [ 6.90486178e-310,  6.90486178e-310, -1.52628334e+143,
          6.90486178e-310,  6.90486178e-310]],

       [[ 4.36174304e+039,  6.90486192e-310,  6.90486178e-310,
          2.88491846e-278,  6.90486178e-310],
        [ 6.90486178e-310,  9.75343640e-249,  6.90486261e-310,
          6.90486178e-310, -4.21068133e+090],
        [ 6.90486178e-310,  6.90486178e-310,  2.14829574e-265,
          6.90486178e-310,  2.45056560e-321]]])

In [41]:
#Creating identity matrix using  np.eye()

np.eye(4) #will make 4,4 matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
np.linspace(2,3,20) #2-3 divided into 20 parts 



array([2.        , 2.05263158, 2.10526316, 2.15789474, 2.21052632,
       2.26315789, 2.31578947, 2.36842105, 2.42105263, 2.47368421,
       2.52631579, 2.57894737, 2.63157895, 2.68421053, 2.73684211,
       2.78947368, 2.84210526, 2.89473684, 2.94736842, 3.        ])

In [44]:
np.logspace(2,3,10) #return the log values

array([ 100.        ,  129.1549665 ,  166.81005372,  215.443469  ,
        278.25594022,  359.38136638,  464.15888336,  599.48425032,
        774.26368268, 1000.        ])

In [45]:
np.logspace(2,3,10 , base = 2)

array([4.        , 4.32023896, 4.66611616, 5.0396842 , 5.44316   ,
       5.87893797, 6.34960421, 6.85795186, 7.4069977 , 8.        ])

In [46]:
#random function : It will assign random numbers in matrix
#In randn function ,value's mean = o and standard deviation will = 1.

arr  = np.random.randn(4,3) #Will make 4*4 matr4ix with random values

In [47]:
arr

array([[-0.86804536, -0.74723613,  0.3330246 ],
       [-1.68755865,  0.73784991,  0.00575859],
       [ 0.85034886,  0.64192068, -1.02782476],
       [ 0.24875883, -0.78300422, -0.73762214]])

In [48]:
import pandas as pd

In [49]:
#Converting the array int o pandas dataframe using dataframe function 

pd.DataFrame(arr)

0         1         2
0 -0.868045 -0.747236  0.333025
1 -1.687559  0.737850  0.005759
2  0.850349  0.641921 -1.027825
3  0.248759 -0.783004 -0.737622

In [52]:
#randint : it will give random int values 

np.random.randint(1,10,(4,3)) #number - 1 to 10 , 4*3 matrix

array([[7, 7, 1],
       [7, 3, 2],
       [4, 2, 9],
       [2, 4, 7]])

In [56]:
#random,rand : it will give random positive values 

np.random.rand(4,3)

array([[0.28259486, 0.45214451, 0.84032311],
       [0.21580878, 0.57594928, 0.69294576],
       [0.25416743, 0.21482152, 0.31488465],
       [0.38760726, 0.01894127, 0.89173984]])

In [58]:
#Will give random int values accordint to the given range 

df = np.random.randint(1,10,(80,90))

In [59]:
#Converting it into dataframe

df1 = pd.DataFrame(df)

In [60]:
df1

0   1   2   3   4   5   6   7   8   9   ...  80  81  82  83  84  85  86  \
0    8   8   5   7   5   9   1   1   5   8  ...   9   2   8   3   5   3   7   
1    2   4   1   6   5   4   3   9   5   1  ...   9   1   5   7   4   7   7   
2    4   2   3   1   7   4   6   8   3   9  ...   8   7   4   6   9   5   4   
3    6   6   6   1   5   7   5   1   5   3  ...   9   5   4   3   4   5   1   
4    2   2   6   1   2   2   8   3   9   2  ...   7   7   4   7   2   6   6   
..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
75   2   5   2   2   8   5   8   9   9   6  ...   1   7   8   7   6   4   4   
76   3   9   8   4   9   3   5   7   6   4  ...   5   2   1   2   4   4   3   
77   1   6   4   7   2   9   6   1   2   3  ...   9   9   2   1   3   1   5   
78   8   1   9   5   4   1   2   8   6   4  ...   1   1   6   2   4   4   7   
79   9   7   7   2   3   3   1   8   3   1  ...   7   7   9   3   9   3   7   

    87  88  89  
0    3   5   5  
1    3   6   9  
2    3   3   3  
3    5   9   4  
4    1   4   5  
..  ..  ..  ..  
75   3   9   1  
76   8   8   1  
77   2   6   9  
78   8   1   9  
79   2   6   1  

[80 rows x 90 columns]

In [62]:
#Storing all the data into a csv file name test

df1.to_csv('test.csv')

In [63]:
arr = np.random.rand(3,4)

In [64]:
arr

array([[0.6071401 , 0.6562767 , 0.70825392, 0.46042673],
       [0.15648018, 0.11413611, 0.42497708, 0.24623317],
       [0.55392506, 0.32291999, 0.4662884 , 0.68621277]])

In [66]:
# to change the dimension or shape of the array arr
arr.reshape(6,2) #3,4 into 6,2 or we can also make it 2,6 or 4,3

array([[0.6071401 , 0.6562767 ],
       [0.70825392, 0.46042673],
       [0.15648018, 0.11413611],
       [0.42497708, 0.24623317],
       [0.55392506, 0.32291999],
       [0.4662884 , 0.68621277]])

In [68]:
arr1  = arr.reshape(6,-3904980835) #it'll consider the negative values by default 2

In [69]:


arr1

array([[0.6071401 , 0.6562767 ],
       [0.70825392, 0.46042673],
       [0.15648018, 0.11413611],
       [0.42497708, 0.24623317],
       [0.55392506, 0.32291999],
       [0.4662884 , 0.68621277]])

In [70]:
#aceesiing element at 1st row 2nd column

arr1[1][1]

0.46042673427726655

In [72]:
#accessing multiple elements from the array
#accesiing elements at 2,3,4th row and 1 column

arr1[2:5,1]  #from 2 to 5-1 row and from 1st column

array([0.11413611, 0.24623317, 0.32291999])

In [74]:
arr11 = np.random.randint(1,100,(5,5))

In [75]:
arr11

array([[95, 35, 67, 33, 70],
       [20, 84, 11, 73, 55],
       [ 4, 57, 69, 71, 76],
       [15, 90, 87, 15, 37],
       [71,  9, 63,  4, 45]])

In [76]:
#Find the data whoch is greater than the 50 :

#Step1

arr11 > 50

array([[ True, False,  True, False,  True],
       [False,  True, False,  True,  True],
       [False,  True,  True,  True,  True],
       [False,  True,  True, False, False],
       [ True, False,  True, False, False]])

In [77]:
#Step 2

arr11[arr11>50]

array([95, 67, 70, 84, 73, 55, 57, 69, 71, 76, 90, 87, 71, 63])

In [78]:
arr11[2:4,1:3]

array([[57, 69],
       [90, 87]])

In [79]:
arr11[0][0]

95

In [80]:
#channgin value at 0,0

arr11[0][0] = 99

In [81]:
arr11


array([[99, 35, 67, 33, 70],
       [20, 84, 11, 73, 55],
       [ 4, 57, 69, 71, 76],
       [15, 90, 87, 15, 37],
       [71,  9, 63,  4, 45]])

.

In [82]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [84]:
arr1 * arr2 #nornal nultiplication not matrix multiplication

array([[1, 2, 2],
       [2, 4, 2],
       [2, 4, 4]])

In [85]:
arr1 - arr2

array([[ 0,  1, -1],
       [ 1,  0, -1],
       [-1,  0,  0]])

In [86]:

arr1/arr2

array([[1. , 2. , 0.5],
       [2. , 1. , 0.5],
       [0.5, 1. , 1. ]])

In [90]:
#To perfrom the matrix multiplication Using @ function 

arr1@arr2

array([[ 5,  7,  8],
       [ 6,  8, 10],
       [ 7,  9, 10]])

In [92]:
arr1/0 #Will  return infinity not error like we get in python 

/tmp/ipykernel_2925/2189651139.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0 #Will  return infinity not error like we get in python


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [93]:
#Cubing every eleemnt 

arr1**3

array([[1, 8, 1],
       [8, 8, 1],
       [1, 8, 8]])

Broadcasting in array 

In [94]:
arr1**3

array([[1, 8, 1],
       [8, 8, 1],
       [1, 8, 8]])

In [96]:
arr = np.zeros(4)

In [97]:
arr

array([0., 0., 0., 0.])

In [98]:
arr = np.zeros((4,4))

In [99]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [100]:
row = np.array([1,2,3,4])

In [101]:
row

array([1, 2, 3, 4])

In [102]:
#Adding the element in each row

arr  + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [103]:
#we can add any number directly like we are adding the rows
arr+1009

array([[1009., 1009., 1009., 1009.],
       [1009., 1009., 1009., 1009.],
       [1009., 1009., 1009., 1009.],
       [1009., 1009., 1009., 1009.]])

In [104]:
#Now adding same values in columns instead of the row
#first we have to convert the matrix into 2d to transpose it
#Then we have to transpose the matrix

col = np.array([[1,2,3,4]]) #using two brackets wil make it 2d array

In [105]:
col

array([[1, 2, 3, 4]])

In [107]:
col1 = col.T #trandposed by 180 degree

In [108]:
col1

array([[1],
       [2],
       [3],
       [4]])

In [109]:
col1 +arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [111]:
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [112]:
arr1 = np.random.randint(1,4,(3,4))

In [113]:
arr1

array([[3, 3, 3, 3],
       [2, 3, 1, 1],
       [3, 1, 1, 1]])

In [114]:
np.sqrt(arr1) #Finding the sqrt of all the elements

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [1.41421356, 1.73205081, 1.        , 1.        ],
       [1.73205081, 1.        , 1.        , 1.        ]])

In [115]:
np.square(arr1)

array([[9, 9, 9, 9],
       [4, 9, 1, 1],
       [9, 1, 1, 1]])

In [118]:
a =np.cumsum(arr1)

In [119]:
pd.DataFrame(a)

0
0    3
1    6
2    9
3   12
4   14
5   17
6   18
7   19
8   22
9   23
10  24
11  25