In [1]:
import numpy as np

Sort , Search and Counting function

In [3]:
arr = np.array([4,2,5,6,7,9,3,6,8,9,11,14,43])

In [4]:
arr

array([ 4,  2,  5,  6,  7,  9,  3,  6,  8,  9, 11, 14, 43])

In [5]:
#Sorting the arrayy 

np.sort(arr)

array([ 2,  3,  4,  5,  6,  6,  7,  8,  9,  9, 11, 14, 43])

In [9]:
#Will tell on which index the entered element will be in sorted list or data
np.searchsorted(arr,40)

12

In [10]:
np.searchsorted(arr , 1)

0

In [11]:
#to find that how many data there are non zero


arr1 = np.array([0.454,345,0,0,0,0,0])

In [12]:
np.count_nonzero(arr1)

2

In [13]:
arr

array([ 4,  2,  5,  6,  7,  9,  3,  6,  8,  9, 11, 14, 43])

In [14]:
#Find out which data is more than six and whats its index using where clause
#data here is unsorted

np.where(arr>6)

(array([ 4,  5,  8,  9, 10, 11, 12]),)

In [15]:
#Extract data which is greater than the six
#this will in sorted form

np.extract(arr > 6, arr)

array([ 7,  9,  8,  9, 11, 14, 43])

In [16]:
#It will convert the data into bytes
arr.byteswap()

array([ 288230376151711744,  144115188075855872,  360287970189639680,
        432345564227567616,  504403158265495552,  648518346341351424,
        216172782113783808,  432345564227567616,  576460752303423488,
        648518346341351424,  792633534417207296, 1008806316530991104,
       3098476543630901248])

In [18]:
#Numpy - Copies and Views

In [19]:
arr

array([ 4,  2,  5,  6,  7,  9,  3,  6,  8,  9, 11, 14, 43])

In [20]:
#Deep copy
#Here ,changes made in a will not apply on arr and vice versa
#It creates another space 
a = np.copy(arr)

In [21]:
a[1] = 9

In [22]:
a

array([ 4,  9,  5,  6,  7,  9,  3,  6,  8,  9, 11, 14, 43])

In [24]:
#arr remains same after replacing the index 1 value in a
arr


array([ 4,  2,  5,  6,  7,  9,  3,  6,  8,  9, 11, 14, 43])

In [25]:
#Swallow copy using views
#changes will apply on both the b and arr
b = arr.view()

In [26]:
b

array([ 4,  2,  5,  6,  7,  9,  3,  6,  8,  9, 11, 14, 43])

In [27]:
arr

array([ 4,  2,  5,  6,  7,  9,  3,  6,  8,  9, 11, 14, 43])

In [28]:
b[1] = 21

In [29]:
b

array([ 4, 21,  5,  6,  7,  9,  3,  6,  8,  9, 11, 14, 43])

In [30]:
arr

array([ 4, 21,  5,  6,  7,  9,  3,  6,  8,  9, 11, 14, 43])

In [31]:
#Numpy : Matrix Librare

In [32]:
import numpy.matlib as nm

In [44]:

p = nm.zeros(6)

In [45]:
p

matrix([[0., 0., 0., 0., 0., 0.]])

In [47]:
#reshaping the matrix 

p.reshape(3,2)

matrix([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [48]:
type(p)

numpy.matrix

In [49]:
p.dtype

dtype('float64')

In [50]:
#Create matrix of ones (1)
nm.ones(6)

matrix([[1., 1., 1., 1., 1., 1.]])

In [52]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [54]:
#creating 5x5 identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
#Numpy : Linear algebra


In [103]:
arr1 = np.random.randint([[3,5], [4,3]]) #Here 3,5 representing first row nd 4,3 representing 2nd row
arr2 = np.random.randint([[5,3] , [2,5]])

In [104]:
arr1

array([[1, 2],
       [3, 2]])

In [105]:
arr2

array([[0, 1],
       [1, 1]])

In [106]:
#Doing matrix multiplication by .dot function

np.dot(arr1 , arr2)

array([[2, 3],
       [2, 5]])

In [107]:
#doing matrix multipllication using @ function
arr1 @ arr2

array([[2, 3],
       [2, 5]])