Numpy : NumPy can be used to perform a wide variety of mathematical operations on arrays. It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.

In [2]:
import numpy as np

In [3]:
#Createing a list 

l = [1,2,3,4,]

In [5]:
l

[1, 2, 3, 4]

In [6]:
#Here we can see , type of l is list 
type(l)

list

In [7]:
#Converting it into array using np.array() function -

ar = np.array(l)

In [8]:
ar

array([1, 2, 3, 4])

In [10]:
#Type of ar is now 1d array
type(ar)

numpy.ndarray

In [12]:
#Making a 2d array 
#! bracket = 1f array, 2[[]] bracket = 2d array

#The np.array() in Python is used to convert a list, tuple, etc. into a Numpy array.

np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [14]:
#We Can also  implement array using asarray
#The numpy.asarray()function is used when we want to convert the input to an array. 
#Input can be lists, lists of tuples, tuples, tuples of tuples, tuples of lists and arrays

np.asarray(l)

array([1, 2, 3, 4])

In [15]:
a = [2,3,4]

In [17]:
#Can also conver it into array using as any array

np.asanyarray(a)

array([2, 3, 4])

Numpy array VS Numpy asarray-

In Python, NumPy array and NumPy asarray are used to convert the data into ndarray. If we talk about the major difference that is when we make a NumPy array using np.array, it creates a copy of the object array or the original array and does not reflect any changes made to the original array. Whereas on the other hand, when we try to use NumPy asarray, it would reflect all the changes made to the original array.

In [18]:
#Converting it into matrix
#its 2d because matrix is alwasy in 2d form

m = np.matrix(l)

In [19]:
m

matrix([[1, 2, 3, 4]])

In [21]:
type(m) #Type is matrix now

numpy.matrix

In [22]:
 #asasny array will not convert matrix into array whereas array will
    
np.asanyarray(m)

matrix([[1, 2, 3, 4]])

In [23]:
a = np.array(l)

In [24]:
a

array([1, 2, 3, 4])

In [26]:
c = a

In [27]:
c[0] = 111 #It will change both the c and a values #Swallow copy

In [28]:
c

array([111,   2,   3,   4])

In [30]:
 #Here we can see changes are made in both the c and a
a

array([111,   2,   3,   4])

In [32]:
#deep copy,changes made in a will not apply in d and vice versa

d = np.copy(a) #d will allocate new space for data.

In [33]:
d 

array([111,   2,   3,   4])

In [35]:
a,d #Currenlty both are same as we have not made any change yet

(array([111,   2,   3,   4]), array([111,   2,   3,   4]))

In [36]:
a[2] = 222

In [37]:
d #As we can see no change is made in d

array([111,   2,   3,   4])

In [39]:
a #But change is made in a ,as it allocated seperate space for the a

array([111,   2, 222,   4])

In [40]:
d[3] =  1060

In [41]:

a #Again no change happneded in a

array([111,   2, 222,   4])

In [43]:
d #Change only happned in d

array([ 111,    2,    3, 1060])