Numpy Array Manipulation 

In [1]:

import numpy as np

In [3]:
#creating a 3x4 matrix

arr = np.random.randint(1,10,(3,4))

In [4]:
arr

array([[9, 7, 2, 4],
       [4, 6, 3, 5],
       [6, 4, 5, 4]])

In [5]:

arr.reshape(6,2)

array([[9, 7],
       [2, 4],
       [4, 6],
       [3, 5],
       [6, 4],
       [5, 4]])

In [6]:

arr.reshape(2,6)

array([[9, 7, 2, 4, 4, 6],
       [3, 5, 6, 4, 5, 4]])

In [7]:
#Transposing matrix by the 180 degree

arr.T

array([[9, 4, 6],
       [7, 6, 4],
       [2, 3, 5],
       [4, 5, 4]])

In [8]:
#Converting 2d array into 1dimension using .flatten() function 

arr.flatten()

array([9, 7, 2, 4, 4, 6, 3, 5, 6, 4, 5, 4])

In [10]:
arr1 = np.array([1,2,3,4])

In [11]:
arr1

array([1, 2, 3, 4])

In [13]:
arr1.ndim #Checking the dimension of the array 

1

In [14]:
#Changing the dimension from 1d to 2d

yy = np.expand_dims(arr1, axis = 1)

In [15]:
yy

array([[1],
       [2],
       [3],
       [4]])

In [16]:
xy = yy.T

In [17]:
xy

array([[1, 2, 3, 4]])

In [18]:
xy.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [19]:
np.squeeze(arr) #Squeeze not performing accordint to expectation

array([[9, 7, 2, 4],
       [4, 6, 3, 5],
       [6, 4, 5, 4]])

In [20]:
#So creatinf a new data 
data = np.array([[1] , [2] , [3]])

In [21]:
data

array([[1],
       [2],
       [3]])

In [22]:
#squeezing data into 1 deimension
np.squeeze(data)

array([1, 2, 3])

In [26]:
arr1

array([1, 2, 3, 4])

In [23]:
#repeat elements given times #3 times

np.repeat(arr1,3)


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [28]:
#will shift , roll according to given number

np.roll(arr1,2)

array([3, 4, 1, 2])

In [29]:
np.roll(arr1,3)

array([2, 3, 4, 1])

In [32]:
np.roll(arr1,3) #Shifing sll the element 3times 
#index of 1 was zero but after shifting its on 3
#index of 2 was one but after shifting its on 0 and so on

array([2, 3, 4, 1])

In [33]:
#it will put gives matrix in diagonal form 

np.diag(arr1)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#Binary operation [= , - , x , /]

In [34]:
arr1 = np.random.randint(1,10 , (3,4))
arr2 = np.random.randint(1,10 , (3,4))

In [35]:

arr1

array([[2, 7, 8, 8],
       [3, 6, 9, 7],
       [6, 7, 1, 2]])

In [36]:
arr2

array([[4, 8, 4, 7],
       [3, 7, 3, 9],
       [4, 9, 8, 8]])

In [37]:
arr1 +arr2

array([[ 6, 15, 12, 15],
       [ 6, 13, 12, 16],
       [10, 16,  9, 10]])

In [38]:
arr1/arr2


array([[0.5       , 0.875     , 2.        , 1.14285714],
       [1.        , 0.85714286, 3.        , 0.77777778],
       [1.5       , 0.77777778, 0.125     , 0.25      ]])

In [39]:
arr1*arr2 #not matrix multiplication

array([[ 8, 56, 32, 56],
       [ 9, 42, 27, 63],
       [24, 63,  8, 16]])

In [40]:
#remainder operation
arr1 % arr2

array([[2, 7, 0, 1],
       [0, 6, 0, 7],
       [2, 7, 1, 2]])

In [41]:
arr1 ** arr2

array([[      16,  5764801,     4096,  2097152],
       [      27,   279936,      729, 40353607],
       [    1296, 40353607,        1,      256]])

In [42]:
#perforaming AND operation on arr1 ,arr2
arr1 & arr2

array([[0, 0, 0, 0],
       [3, 6, 1, 1],
       [4, 1, 0, 0]])

In [43]:
arr2

array([[4, 8, 4, 7],
       [3, 7, 3, 9],
       [4, 9, 8, 8]])

In [44]:
#negate operation #Turn into negative values
-arr1

array([[-2, -7, -8, -8],
       [-3, -6, -9, -7],
       [-6, -7, -1, -2]])

In [45]:
#Performing or OR operation

arr1 | arr2

array([[ 6, 15, 12, 15],
       [ 3,  7, 11, 15],
       [ 6, 15,  9, 10]])

In [49]:
arr1 > arr2

array([[False, False,  True,  True],
       [False, False,  True, False],
       [ True, False, False, False]])

In [50]:
arr1[arr1>arr2]

array([8, 8, 9, 6])

In [51]:
arr = np.array(["shad" , "khan"])

In [52]:
arr

array(['shad', 'khan'], dtype='<U4')

In [53]:
np.char.upper(arr)

array(['SHAD', 'KHAN'], dtype='<U4')

In [54]:
np.char.title(arr)

array(['Shad', 'Khan'], dtype='<U4')